name: Main

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get current day
        id: current-day
        run: |
          echo "CURRENT_DAY=$(date +"%u")" >> "$GITHUB_OUTPUT"
      - name: Is it Sunday?
        if: ${{ steps.current-day.outputs.CURRENT_DAY == '7' }}
        run: echo "It is Sunday!"
      - name: Is it Thursday?
        if: ${{ steps.current-day.outputs.CURRENT_DAY == '4' }}
        run: echo "It is Thursday!"
